FILE_COLUMNS = {
    "template_internal_ref": "product_tmpl_id.default_code",
    "template_name": "product_tmpl_id.name",
    "template_functional_category": "product_tmpl_id.categ_id.name",
    "template_regular_price": "product_tmpl_id.regular_price",
    "template_sales_price": "product_tmpl_id.list_price",
    "template_web_categories": "product_tmpl_id.public_categ_ids.name",
    "template_tags": "product_tmpl_id.product_tag_ids.name",
    "template_images_url": "product_tmpl_id.image_url_ids.url",
    "variant_internal_ref": "default_code",
    "variant_regular_price": "regular_price",
    "variant_barcodes": "barcode",
    "variant_tags": "product_tag_ids.name",
    "variant_vendor_name": "variant_seller_ids.partner_id.name",
    "variant_vendor_product_name": "variant_seller_ids.product_name",
    "variant_vendor_product_code": "variant_seller_ids.product_code",
    "variant_vendor_price": "variant_seller_ids.price",
    "variant_vendor_quantity": "variant_seller_ids.min_qty",
}

TYPE_COLUMNS = {
    "template_internal_ref": str,
    "template_name": str,
    "template_functional_category": str,
    "template_regular_price": float,
    "template_sales_price": float,
    "template_web_categories": str,
    "template_tags": str,
    "variant_internal_ref": str,
    "variant_regular_price": float,
    "variant_barcodes": str,
    "variant_tags": str,
    "variant_vendor_name": str,
    "variant_vendor_product_name": str,
    "variant_vendor_product_code": str,
    "variant_vendor_price": float,
    "variant_vendor_quantity": float,
}
