# -*- coding: utf-8 -*-

{
    'name': "Mataa Order Management",
    'summary': "Mataa Order Management",
    'description': "Mataa Order Management",

    'author': "Websers",
    'website': "https://websers.odoo.com",
    'license': 'OPL-1',

    'category': 'Mataa',
    'version': '6.3',

    'depends': ['base', 'account', 'sale', 'sale_margin', 'analytic', 'contacts', 'purchase', 'sale_management',
                'sales_team', 'stock_delivery', 'stock_picking_batch', 'helpdesk',
                'purchase_requisition', 'mataa_base', 'mataa_external_sync', 'mataa_customer_management',
                'mataa_base_delivery', 'mrp',
                'stock_barcode_picking_batch', 'mataa_product_management', 'stock_barcode', 'stock', 'stock_account',
                'sale_loyalty', 'account_reports'],

    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'security/mataa_security.xml',

        'data/ir_action_data.xml',
        'data/ir_seq_data.xml',
        'data/sale_order_tag_data.xml',
        'data/vendor_payment_cron.xml',
        'data/multi_unpack_action.xml',
        'data/payment_cron.xml',
        'data/finance_tags_data.xml',

        'reports/layout.xml',
        'reports/invoice_template.xml',
        'reports/invoice_report.xml',
        'reports/so_template.xml',
        'reports/so_report.xml',
        'reports/mataa_in_house_report_by_location_view.xml',
        'reports/mataa_in_house_report_by_product_view.xml',
        'reports/mataa_in_house_report_per_vendor_view.xml',
        'reports/sale_order_line_report_view.xml',
        'reports/barcode_number_report.xml',
        'reports/picking_draft_report.xml',
        'reports/component_sale_report_view.xml',
        'reports/report_picking_inherit.xml',
        'reports/vendor_return_location_report_view.xml',
        'reports/batch_products_report.xml',
        'reports/purchase_report_templates.xml',
        'reports/sale_order_cancel_report.xml',
        'reports/picking_batch_report.xml',
        'reports/account_general_view.xml',

        'views/account_journal_view.xml',
        'views/account_move_view.xml',
        'views/account_payment_view.xml',
        'views/help_ticket_view.xml',
        'views/res_partner_view.xml',
        'views/res_config_settings_view.xml',
        'views/purchase_order_view.xml',
        'wizard/switch_payment_method_wizard.xml',
        'views/sale_order_view.xml',
        'views/purchase_order_view.xml',
        'views/purchase_requisition_views.xml',
        'views/stock_picking_batch_view.xml',
        'views/stock_picking_view.xml',
        'views/stock_scrap_view.xml',
        'views/vendor_page_views.xml',
        'views/product_supplierinfo_views.xml',
        'views/product_vendor_blacklist_view.xml',
        'views/sale_order_line_rejection_views.xml',
        'views/sale_bulk_filter_wizard_view.xml',
        'views/stock_views.xml',
        'views/stock_orderpoint_view.xml',
        'views/stock_picking_invoice_view.xml',
        'views/sale_order_report_views.xml',
        'views/product_template.xml',
        'views/loyalty_view.xml',
        'views/loyalty_reward_view.xml',
        'views/replenishment_sold_qty_view.xml',
        'views/stock_quant_view.xml',
        'views/stock_valuation_layer_view.xml',
        'wizard/vendor_bill_discount_wizard_view.xml',

        'wizard/bundle_pack_confirmation_wizard.xml',
        'wizard/price_adjustement_views.xml',
        'wizard/sol_reject_wizard.xml',
        'wizard/orders_closing_wizard.xml',
        'wizard/replenishment_snooze_wizard_view.xml',
        'views/price_adjustement_history_views.xml',
        'wizard/import_packages_wizard_views.xml',
        'views/compensation_reason_view.xml',
        'wizard/sale_order_compensation_wizard.xml',
        'wizard/refund_reason_wizard_views.xml',
        'wizard/sale_coupon_wizard_view.xml',
        'wizard/validation_wizard_view.xml',
        'wizard/order_cancel_wizard_view.xml',
		'wizard/choose_package_wizard_view.xml',
        'wizard/sale_suspension_wizard_view.xml',
],

    'installable': True,
    'application': True,

    'controllers': [
        'controllers/dtrack_controller.py',
        'controllers/sale_order_controller.py',
        'controllers/vendor_controller.py',
        'controllers/vendor_tag_controller.py',
    ],
    'application': True,

    'assets': {
        'web.assets_backend': [
            'mataa_order_management/static/src/js/stock_orderpoint_expand_groups.js',
            'mataa_order_management/static/src/xml/stock_orderpoint_expand_groups.xml',
            'mataa_order_management/static/src/js/duplicate_confirmation.js',
            'mataa_order_management/static/src/js/barcode_picking_model.js',
            'mataa_order_management/static/src/xml/main.xml',
            'mataa_order_management/static/src/xml/barcode_line.xml',
        ],
    }
}
