# -*- coding: utf-8 -*-

from . import account_journal
from . import account_move
from . import account_move_line
from . import account_payment
from . import help_ticket
from . import purchase_order
from . import sale_order
from . import sale_order_coupon
from . import sale_order_line
from . import sale_order_tag
from . import sale_order_bundle
from . import res_partner
from . import res_config_settings
from . import purchase_order_line
from . import stock_picking
from . import purchase_requisition
from . import purchase_requisition_line
from . import stock_picking_batch
from . import stock_move
from . import stock_move_line
from . import product_supplierinfo
from . import product_vendor_blacklist
from . import stock_scrap
from . import sale_order_line_rejection
from . import stock_warehouse_orderpoint
from . import price_adjustement_history
from . import account_move_price_alerts
from . import compensation_reason
from . import sale_order_price_alerts
from . import stock_picking_invoice
from . import sale_order_price_alerts
from . import loyalty_program
from . import loyalty_rule
from . import sale_order_reason
from . import price_adjustment_reason
from . import product_template
from . import loyalty_reward
from . import order_cancel_reason
from . import payment_cron
from . import stock_quant
from . import mataa_note_tag_rule
from . import stock_valuation_layer
